<a href="https://colab.research.google.com/github/Kolosafo/data_preprocessing/blob/master/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTING LIBRARIES

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('salary.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[['nigeria' 27.0 72000.0]
 ['ghana' nan 48000.0]
 ['cameroon' 39.0 52000.0]
 ['ghana' 23.0 33000.0]
 ['ghana' nan nan]
 ['nigeria' 40.0 32300.0]
 ['cameroon' 32.0 24000.0]
 ['nigeria' 28.0 66000.0]
 ['nigeria' nan nan]
 ['ghana' 26.0 55000.0]]


In [5]:
print(y)

['no' 'yes' 'yes' 'no' 'yes' 'yes' 'no' 'no' 'no' 'yes']


HANDLING MISSING DATA


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy="mean")
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [7]:
print(X)

[['nigeria' 27.0 72000.0]
 ['ghana' 30.714285714285715 48000.0]
 ['cameroon' 39.0 52000.0]
 ['ghana' 23.0 33000.0]
 ['ghana' 30.714285714285715 47787.5]
 ['nigeria' 40.0 32300.0]
 ['cameroon' 32.0 24000.0]
 ['nigeria' 28.0 66000.0]
 ['nigeria' 30.714285714285715 47787.5]
 ['ghana' 26.0 55000.0]]


ENCODING CATEGORICAL DATA

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [("encoder", OneHotEncoder(), [0])], remainder = "passthrough")
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[0.0 0.0 1.0 27.0 72000.0]
 [0.0 1.0 0.0 30.714285714285715 48000.0]
 [1.0 0.0 0.0 39.0 52000.0]
 [0.0 1.0 0.0 23.0 33000.0]
 [0.0 1.0 0.0 30.714285714285715 47787.5]
 [0.0 0.0 1.0 40.0 32300.0]
 [1.0 0.0 0.0 32.0 24000.0]
 [0.0 0.0 1.0 28.0 66000.0]
 [0.0 0.0 1.0 30.714285714285715 47787.5]
 [0.0 1.0 0.0 26.0 55000.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[0 1 1 0 1 1 0 0 0 1]


SPLITTTING DATASET INTO TRAINING AND TESTSET

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=.8, random_state=1)

In [13]:
print(X_train)

[[1.0 0.0 0.0 32.0 24000.0]
 [0.0 1.0 0.0 30.714285714285715 47787.5]
 [0.0 0.0 1.0 27.0 72000.0]
 [0.0 1.0 0.0 23.0 33000.0]
 [0.0 1.0 0.0 30.714285714285715 48000.0]
 [0.0 0.0 1.0 28.0 66000.0]
 [0.0 0.0 1.0 30.714285714285715 47787.5]
 [0.0 0.0 1.0 40.0 32300.0]]


In [14]:
print(X_test)

[[1.0 0.0 0.0 39.0 52000.0]
 [0.0 1.0 0.0 26.0 55000.0]]


In [15]:
print(y_train)

[0 1 0 0 1 0 0 1]


In [16]:
print(y_test)

[1 1]


FEATURE SCALING

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [20]:
print(X_train)

[[1.0 0.0 0.0 0.37916379579549686 -1.4410239555873277]
 [0.0 1.0 0.0 0.0977226277823447 0.09204024426322974]
 [0.0 0.0 1.0 -0.7153296353667624 1.6524949763234134]
 [0.0 1.0 0.0 -1.5909243802965698 -0.8609891558540637]
 [0.0 1.0 0.0 0.0977226277823447 0.1057355103680429]
 [0.0 0.0 1.0 -0.4964309491343106 1.2658051098345708]
 [0.0 0.0 1.0 0.0977226277823447 0.09204024426322974]
 [0.0 0.0 1.0 2.130353285655112 -0.9061029736110953]]


In [21]:
print(X_test)

[[1.0 0.0 0.0 1.9114545994226597 0.36352875469393797]
 [0.0 1.0 0.0 -0.9342283215992142 0.5568736879383593]]
